version: '3.5'
name: news_service

services:
    web.facade:
        container_name: news_webfacade
        image: news_webfacade
        ports:
            - "5283:80"
        build: '../'
        environment:
            ConnectionStrings__DatabaseConnection: 'Data Source=mssql_server; Initial Catalog=NewsService; User ID=SA; Password=Adminadmin1@'
        networks:
            - app_bridge_network

networks:
    app_bridge_network:
        name: app_bridge_network
        driver: bridge
        external: true